# Generated by Django 4.0.3 on 2022-04-08 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='join',
            field=models.DateField(default=datetime.datetime(2022, 4, 8, 20, 4, 59, 178962), verbose_name='date'),
        ),
    ]
