# Generated by Django 4.0.3 on 2022-04-08 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_join'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phonr',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='employee',
            name='join',
            field=models.DateField(default=datetime.datetime(2022, 4, 8, 20, 6, 55, 977666), verbose_name='date'),
        ),
    ]
