# Generated by Django 4.0.3 on 2022-04-08 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_phonr_employee_phone_alter_employee_join'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='addreee',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='employee',
            name='join',
            field=models.DateField(default=datetime.datetime(2022, 4, 8, 20, 26, 48, 449575), verbose_name='date'),
        ),
    ]
